// 05 Server/tic-tac-toe - websockets/src/components/Waiting.vue
<script setup lang="ts">
  import * as api from '@/api/api'
  import { defineProps, onMounted, onUnmounted } from 'vue'
  import { store } from '@/api/store';
  const model = store()

  const props = defineProps<{gameNumber: number}>()

  const ws = new WebSocket('ws://localhost:9090/publish')

  onMounted(() => { 
    ws.onopen = () => ws.send(JSON.stringify({type: 'subscribe', key: 'game_' + props.gameNumber}))
    ws.onmessage = ({data}) => {
      const {message: {ongoing, ...game}} = data
      if (ongoing) model.startGame('X', game)
    }    
  })
  onUnmounted(() => { 
    ws.send(JSON.stringify({type: 'unsubscribe'}))
    ws.close()
  })

  async function waitForPlayer() {
    const game = await api.readGame(props.gameNumber)
    if (game.ongoing)
      model.startGame('X', game)
    else 
      setTimeout(waitForPlayer, 100)
  }

  onMounted(waitForPlayer)
</script>

<template>
  <h1>Waiting for other player...</h1>
</template>

// 11 Next JS/tic-tac-toe - api - full/src/components/Waiting.tsx
'use client'

import { Game } from "@/lib/model"
import { useRouter } from "next/navigation"
import { useEffect } from "react"

export const Waiting = ({id, name}: {id: number, name: string}) => {
  const router = useRouter()

  useEffect(() => {
    const ws = new WebSocket('ws://localhost:9090/publish')
      
    ws.onopen = () => {
      ws.send(JSON.stringify({type: 'subscribe', key: 'game_' + id}))
    }

    ws.onmessage = ({data}) => {
      const {message}: {message: Game} = JSON.parse(data)
      if (message.ongoing)
        router.replace(`/play/${id}?player=X`)
    }

    return () => { 
      if (ws.readyState === WebSocket.OPEN) 
        ws.close() 
    }
  }, [id])

return <div>
    <h2>Waiting on opponent for game {name}</h2>
  </div>
}
